Improve Error Handling for tt-steps (#138)
jenkinsci/ecu-test-execution-plugin pull request #145
Opened 2024-05-31 10:10 UTC by MarioFuchsTT

Resolves #138

2024-06-04 07:37 UTC, MartinGroscheTT requested changes
* do we need to adapt this [line ](https://github.com/jenkinsci/ecu-test-execution-plugin/blob/3058dad11ed769d8bd6e82ca5dee2a02c291cb6d/src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy#L151) as well
* getExeFileOnNode still throws an IllegalArgumentException -> please check all classes for adaption needed
* no tests found for those code changes

2024-06-04 07:37 UTC, MartinGroscheTT commented on src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunTestFolderStep.groovy
> +        } catch (IOException | InterruptedException e) {
Do not found InterruptedException

2024-06-04 07:37 UTC, MartinGroscheTT commented on src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy
> +                                "Please ensure that tracetronic tools are not already stopped.")
It is also possible that some process is blocked and we run into a timeout as a result

2024-06-04 07:37 UTC, MartinGroscheTT commented on src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy
> +                        "Please ensure the tool is running and its API endpoint is accessible.")
If the tool is started correctly, the endpoint can be reached. The user has no possibility to check the endpoint separately

2024-06-07 11:14 UTC, MarioFuchsTT commented
> * do we need to adapt this [line ](https://github.com/jenkinsci/ecu-test-execution-plugin/blob/3058dad11ed769d8bd6e82ca5dee2a02c291cb6d/src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStep.groovy#L151) as well

For those, exceptions are now caught and converted to an AbortException, along with their messages.


> * getExeFileOnNode still throws an IllegalArgumentException -> please check all classes for adaption needed

This will now be handled within the catch block of its calling method.

2024-06-17 14:04 UTC, MartinGroscheTT approved these changes

2024-06-18 06:34 UTC, merged