provide documentation for advanced usage (#165)
jenkinsci/ecu-test-execution-plugin pull request #176
Opened 2024-09-10 11:02 UTC by MxEh-TT

Closes #165

2024-09-19 14:31 UTC, MartinGroscheTT requested changes

2024-09-19 14:31 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +| Step-Name         | Parameters
i expected something like a java [doc ](https://javadoc.jenkins.io/hudson/model/Hudson.html) or a unique implementation of that.
| Method | Description | Parameters | Returns |
|--------|-------------|------------|---------|
| `ttCheckPackage` | Run an ecu.test package  | - `testCasePath`: `String `- Description<br/> - `packageConfig`: [`PackageConfig`](#packageconfig)  - description <br/> - `analysisConfig`: [`AnalysisConfig`](#analysisconfig) - description| [`TestResult`](#testresult) - description |

2024-09-19 14:31 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +| ttRunPackage      | testCasePath: String,<br/> packageConfig: [PackageConfig](#packageconfig) <br/> analysisConfig: [AnalysisConfig](#analysisconfig)
Missing `testConfig`, please check properties

2024-09-19 14:31 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +# Input Objects and their properties
I guess i would only describe objects. Doesn't matter if its an param or return

2024-09-19 14:31 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +## ScanMode
why is this a code snippet instead of a table?

2024-09-19 14:31 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
With this implementation, I have to remember to update the file myself every time.
- Either:
  - we keep our code documentation, the specs and tests up to date 
    - with all their link to referenced classes 
    - a object spec as yml
  - and generate the documentation
- Or:
  - update the documentation manually
  - run test from code snippets out of this documentation 
  - this does not guarantee the actuality

2024-09-24 08:16 UTC, MxEh-TT commented on docs/AdvancedUsage.md
added idea to jira to generate the docs automatically, as discussed

2024-09-24 14:50 UTC, MartinGroscheTT requested changes

2024-09-24 14:50 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +| **testResult**: String | Result of the package / project execution |
should we add the possible results here? Or user can only check if the report ID is empty

2024-09-24 14:50 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +| **testResult**: String | Result of the package / project execution |
We should keep it more generic for objects used by different steps. See `project archive or analysis job`

2024-09-24 14:50 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +| **ttRunPackage**      | **testCasePath**: String - The path to the test case file that should be started. A test case file can be a package, project, project archive or analysis job. The path must
ecu**.**test

fix that within the whole file

2024-09-24 14:50 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +| **forceConfigurationReload**: boolean       | false         | If true, always reload the configuration even if the same one is still active. Hint: This flag is only required for ecu.test versions l
i guess it is not possible to ignore that flag because it has a default value

2024-09-24 14:50 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +| **ttRunProject**      | **testCasePath**: String - The path to the test case file that should be started. A test case file can be a package, project, project archive or analysis job. The path must
run package should reference packages for the testCasePath and run project should reference projects

2024-09-24 14:50 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +| **ttRunTestFolder**   | **testCasePath**: String - Absolute test folder path where packages/projects are located. <br/><br/> **testConfig**: [TestConfig](#testconfig) - Contains settings for the ec
missing the description for the scanMode

2024-09-24 14:50 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +| enum **ScanMode** | PACKAGES_ONLY <br/><br/> PROJECTS_ONLY <br/><br/> PACKAGES_AND_PROJECTS |
* Describe the behavior
* in case of a pipeline definition enums will be set as strings

2024-09-24 14:50 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +| **ttUploadReports**   | **testGuideUrl**: String - The URL to the test.guide instance to connect to <br/><br/> **credentialsId**: String - Credentials for test.guide REST API.<br/><br/>**projectId*
`**reportIds**: List<String> - List  ...` you already typed it as a list

2024-09-24 14:50 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +| **uploadResult**: String  | Result of the report upload to test guide. |
Which upload results are possible or how can the user check if the upload was successful?
Failed uploads has no `reportLink`

2024-09-24 14:50 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +            testGuideUrl: '',
use placeholder as well

2024-09-30 10:55 UTC, MartinGroscheTT requested changes

2024-09-30 10:55 UTC, MartinGroscheTT commented on docs/AdvancedUsage.md
> +| **ttUploadReports**   | **testGuideUrl**: String - The URL to the test.guide instance to connect to <br/><br/> **credentialsId**: String - Credentials for test.guide REST API.<br/><br/>**projectId*
lets be a bit more specific here. 
`reportdIds: List<String>` was fine. I meant that the description starts with _List of reportIds_. That seems to be the same thing in this context.

2024-09-30 13:45 UTC, MartinGroscheTT approved these changes

2024-10-01 07:06 UTC, merged