add provide generated reports step (#159)
jenkinsci/ecu-test-execution-plugin pull request #183
Opened 2024-10-01 14:58 UTC by MxEh-TT

Closes #159

2024-10-10 15:50 UTC, MartinGroscheTT requested changes

2024-10-16 10:28 UTC, ErikRehmTT requested changes
I don't like the sidebar namings: It should be `ecu.test Logs`, `ecu.test Reports` and `Generated ecu.test Reports`

2024-10-16 10:28 UTC, ErikRehmTT commented on src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/ProvideGeneratedReportsStep.groovy
> +            def folderEntryPaths = ZipUtil.getAllMatchingPaths(reportZip, "${reportType}*/**")
`${reportType}*`: I would give the power of matching with wildcard to the user

A check that the reportType is not `*` or `**` should be added and when found skipped

2024-10-16 10:28 UTC, ErikRehmTT commented on src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/ProvideGeneratedReportsStep.groovy
> +            }
This creates a zip with everything that matches. So if two reports match, both are in the same zip. But there should be s separate zip file for each report. Keep in mind, there can be reports in nested projects/subfolders

I would expect the the zip then contains the content of the report folder but NOT the report folder it self on toplevel

2024-10-16 10:28 UTC, ErikRehmTT commented on src/main/resources/de/tracetronic/jenkins/plugins/ecutestexecution/steps/ProvideGeneratedReportsStep/config.jelly
> +        <f:entry title="${%selectedReportTypes.title}" description="${%selectedReportTypes.description}"
this shouldn't be an advanced config option

2024-10-16 10:28 UTC, ErikRehmTT commented on src/main/resources/de/tracetronic/jenkins/plugins/ecutestexecution/steps/ProvideGeneratedReportsStep/config.properties
> +selectedReportTypes.description=Generated report name that should be provided.
Add that it needs to be a comma separated list with the possibility to use wildcards

2024-11-11 14:31 UTC, ErikRehmTT requested changes

2024-11-12 13:36 UTC, ErikRehmTT approved these changes

2024-11-12 13:37 UTC, merged