Increase branch coverage (#205)
jenkinsci/ecu-test-execution-plugin pull request #208
Opened 2024-12-13 09:12 UTC by MarioFuchsTT

Resolves #205

2024-12-19 09:36 UTC, MxEh-TT requested changes

2024-12-19 09:36 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/configs/ExecutionConfigTest.groovy
> +//    }
rm comments

2024-12-19 09:36 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/configs/PublishConfigTest.groovy
> +//    }
rm comments

2024-12-19 09:36 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StartToolStepTest.groovy
> +//    }
rm comments

2024-12-19 09:36 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/StopToolStepTest.groovy
> +//    }
rm comments

2024-12-19 09:36 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/clients/RestApiClientFactoryTest.groovy
test default hostname, port is used and given is trimmed

2024-12-19 09:36 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/model/CheckPackageResultTest.groovy
> +    }
combine

2024-12-19 09:36 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunPackageStepTest.groovy
> +            def context = Mock(StepContext) {
use setup method

2024-12-19 09:36 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunPackageStepTest.groovy
> +            GroovyMock(FilePath, global: true)
see above

2024-12-19 09:36 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunProjectStepTest.groovy
> +            GroovyMock(FilePath, global: true)
setup method

2024-12-19 09:36 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunProjectStepTest.groovy
> +            def projectPath = GroovyMock(FilePath)
see above

2024-12-19 09:36 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunTestFolderStepTest.groovy
> +            testPackageBuilder.runTest() >> testResult
setup method, also check if all needed

2024-12-19 09:36 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunTestFolderStepTest.groovy
> +            testProjectBuilder.runTest() >> testResult
see above

2024-12-19 09:37 UTC, MxEh-TT commented
Note: check Client folder

2025-01-09 15:13 UTC, ErikRehmTT requested changes

2025-01-09 15:13 UTC, ErikRehmTT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/util/ZipUtilTest.groovy
> +    }
Aren't they already tested by `should check for presence of file types`

2025-01-09 15:13 UTC, ErikRehmTT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/util/ZipUtilTest.groovy
> +    }
Already tested by `extract files by extension`

2025-01-20 10:17 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/model/CheckPackageResultTest.groovy
> +    }
currently two empty strings are returning true, is this expected ?

2025-01-20 10:19 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/model/CheckPackageResultTest.groovy
> +    }
since we call == instead of contains it ensures non of the other branches are executed
the test above ensures the branches work if issues are found

2025-01-20 10:56 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunPackageStepTest.groovy
> +            "/foo/bar/test.pkg"            | true       | true
is the actual code here as expected ? we only check if the path exists if the path is absolute, all relative paths pass

2025-01-20 10:57 UTC, MxEh-TT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunPackageStepTest.groovy
> +    def "test checkProjectPath throws AbortException for non-existent project path"() {
for some reason spock does not allow an if statement before the noExceptionThrown() / thrown(Exception) parts, so two tests seem to be needed

2025-01-20 16:51 UTC, MxEh-TT commented on src/main/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunTestFolderStep.groovy
>                  }
Did the failFast actually work before ?

2025-01-27 13:17 UTC, ErikRehmTT requested changes

2025-01-27 13:17 UTC, ErikRehmTT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/steps/RunTestFolderStepTest.groovy
> +            RunTestFolderStep.scanProjects(*_) >> []
This only tests the fail fast for package executions, but not for project executions

2025-01-31 14:22 UTC, ErikRehmTT commented on src/test/groovy/de/tracetronic/jenkins/plugins/ecutestexecution/clients/RestApiClientV2WithIdleHandleTest.groovy
We decided that the this is too hard to test in unit tests and the 409 behavior is tested in several integration tests

2025-01-31 14:32 UTC, ErikRehmTT approved these changes

2025-02-03 08:17 UTC, merged