Add artifact upload (#15)
jenkinsci/ecu-test-execution-plugin pull request #31
Opened 2022-12-08 13:55 UTC by MartinGroscheTT

Resolves #15

2023-02-06 19:49 UTC, ErikRehmTT requested changes

2023-02-09 08:19 UTC, MartinGroscheTT commented on .github/workflows/build.yml
> +            echo "artifact_name==${{ github.ref_name }}" >>$GITHUB_OUTPUT
I guess [not](https://codefresh.io/docs/docs/codefresh-yaml/condition-expression-syntax/#comparisons)

2023-02-15 16:42 UTC, ErikRehmTT commented on .github/workflows/build.yml
> +            echo "artifact_name==${{ github.ref_name }}" >>$GITHUB_OUTPUT
But it is inconsistent: `artifact_name==` (if) and `artifact_name=` (else)

2023-02-15 16:42 UTC, ErikRehmTT commented on Jenkinsfile.internal
> +        label 'windows'
don't we need `docker` as well?

2023-02-16 15:02 UTC, ErikRehmTT approved these changes

2023-02-17 06:23 UTC, merged